language: node_js
node_js:
  - "10"
services: mongodb
before_install:
  - pip install --user codecov istanbul
after_success:
  - codecov --file coverage/lcov.info --disable search
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
