language: node_js
node_js:
  - "10"

before_install: |
  [[ ! -x ~/npm/node_modules/.bin/npm ]] && {
    cd ~/npm && npm install npm@^10
    cd -
  } || true
  export PATH=~/npm/node_modules/.bin:$PATH
