language: node_js
node_js:
  - "node"

before_install: |
  [[ ! -x ~/npm/node_modules/.bin/npm ]] && {
    cd ~/npm && npm install npm@^5
    cd -
  } || true
  export PATH=~/npm/node_modules/.bin:$PATH
